global:
  scrape_interval: 15s # Intervalo para recoger métricas

scrape_configs:
  - job_name: "shopping-service" # Nombre del trabajo
    metrics_path: "/actuator/prometheus" # Ruta para recoger métricas
    static_configs:
      - targets: ["localhost:8085"] # Cambia el puerto si es necesario
