# Server configuration
server:
  port: 8085

# Datasource configuration
spring:
  datasource:
    url: jdbc:h2:mem:invoiceDB
    driverClassName: org.h2.Driver
    username: sa
    password: ''

# H2 Console configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true

# Conexion a Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}