# Server configuration
server:
  port: 8083

# Datasource configuration
spring:
  datasource:
    url: jdbc:h2:mem:productDB
    driverClassName: org.h2.Driver
    username: sa
    password: ''

# H2 Console configuration
  h2:
    console:
      enabled: true
      path: /h2-console

# JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true